### ISSUE TITLE
TempEst Java error on Mojave

### ISSUE THREAD

**Issue by kga1978** [beast-dev/beast-mcmc#1035]
TempEst v1.5.1
Java 8 Update 181
Mac OS 10.14 (Mojave)

TempEst crashes immediately after launch - whether one tries to open the app, or execute the jar file directly from the terminal. The program crashes with the following error:

KGA-ShitBook:Downloads andersen$ java -jar /Applications/Beast/TempEst\ v1.5.1.app/Contents/Resources/Java/tempest.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/AboutHandler
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at jam.mac.Utils.macOSXRegistration(Unknown Source)
	at jam.framework.MultiDocApplication.initialize(Unknown Source)
	at dr.app.tempest.TempEstApp.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 14 more

**Comment by kga1978** [comment]
I think this was due to a conflict with OpenJDK 11 being installed in addition to (the GUI version) of Java 8. Removed OpenJDK 11 and installed Java SE Development Kit 8 took care of the problem.
