### ISSUE TITLE
Java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by weipenegHU** [beast-dev/beast-mcmc#1087]
I came across this problem when running the  TreeAnnotator. I have changed the -Xmx of TreeAnnotator to 10GB but it did not work.
Here are some information that may be helpful.

input tree size: 3.2G
Burn in: 1,000,000 states
Targe tree type: Maximum clade credibility tree
Node heights: Median heights

***Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:748)
	at java.base/java.lang.StringBuffer.append(StringBuffer.java:424)
	at dr.evolution.io.Importer.skipComments(Unknown Source)
	at dr.evolution.io.Importer.readCharacter(Unknown Source)
	at dr.evolution.io.Importer.nextCharacter(Unknown Source)
	at dr.evolution.io.Importer.readToken(Unknown Source)
	at dr.evolution.io.Importer.readDouble(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)
	at dr.evolution.io.NexusImporter.readInternalNode(Unknown Source)
	at dr.evolution.io.NexusImporter.readBranch(Unknown Source)

**Comment by relax991212** [comment]
Hello, I also encountered the same problem, how do you solve it later

**Comment by rambaut** [comment]
You will likely need much more than 10GB to load this tree file. I suggest down sampling it first using LogCombiner.

**Comment by rambaut** [comment]
That won't be necessary. Use `LogCombiner` in the BEAST package to resample your existing log files to a sparser sample.
https://beast.community/logcombiner
