### ISSUE TITLE
Neither the OS X 1.10.4 nor the conda installation of BEAST recognize the beagle libraries

### ISSUE THREAD

**Issue by drdna** [beast-dev/beast-mcmc#1088]
INFO:   BEAGLE function, create, returned error code -6 (No resource matches requirements)
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treedatalikelihood.BeagleDataLikelihoodDelegate.<init>(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.createTreeDataLikelihood(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

LD_LIBRARY_PATH is set

**Comment by rambaut** [comment]
Not an issue with BEAST - likely to do with BEAGLE installation.
