### ISSUE TITLE
BEAGLE function, create, returned error code -6 (No resource matches requirements) but BEAGLE installed

### ISSUE THREAD

**Issue by dl0096** [beast-dev/beast-mcmc#1104]
```
Using BEAGLE library v3.1.0 for accelerated, parallel likelihood evaluation
2009-, BEAGLE Working Group - https://beagle-dev.github.io/
Citation: Ayres et al (2012) Systematic Biology 61: 170-173 | doi:10.1093/sysbio/syr100


Random number seed: 1611243479596


Loading additional development parsers from development_parsers.properties, which is additional set of parsers only available for development version ...
Parsing XML file: infile.xml
  File encoding: UTF8
Looking for plugins in /Volumes/BEAST v1.10.4/plugins

Read alignment: alignment
  Sequences = 34
      Sites = 99
   Datatype = amino acid
Site patterns 'patterns' created from positions 1-99 of alignment 'alignment'
  unique pattern count = 61

Creating the tree model, 'treeModel'
  taxon count = 34
  tree height = 4.267439845283453

Using strict molecular clock model.

Creating site rate model.

Using BEAGLE DataLikelihood Delegate
Jan 21, 2021 3:38:13 PM beagle.BeagleFactory loadBeagleInstance
INFO:   BEAGLE function, create, returned error code -6 (No resource matches requirements)
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treedatalikelihood.BeagleDataLikelihoodDelegate.<init>(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.createTreeDataLikelihood(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

BEAST has terminated with an error. Please select QUIT from the menu.```

**Comment by NikithaSundaresha** [comment]
I have the same issue as well!
Creating the tree model, 'treeModel'
  taxon count = 110
  tree height = 240.915503464774
The gmrfSkyrideLikelihood has time aware smoothing
Creating a GMRF smoothed skyride model:
	Population sizes: 109
	If you publish results using this model, please reference: Minin, Bloomquist and Suchard (2008) Molecular Biology and Evolution, 25, 1459-1471.
Using continuous relaxed clock model.
  parametric model = logNormalDistributionModel
   rate categories = 1

Creating state frequencies model 'frequencies': Initial frequencies = {0.25, 0.25, 0.25, 0.25}

Creating site rate model: 
  4 category discrete gamma with initial shape = 0.5

Using BEAGLE DataLikelihood Delegate
Sep 30, 2021 4:29:47 AM beagle.BeagleFactory loadBeagleInstance
INFO:   BEAGLE function, create, returned error code -6 (No resource matches requirements)
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treedatalikelihood.BeagleDataLikelihoodDelegate.<init>(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.createTreeDataLikelihood(Unknown Source)
	at dr.evomodelxml.treedatalikelihood.TreeDataLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain
BEAST has terminated with an error. Please select QUIT from the menu.
.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

**Comment by rambaut** [comment]
This looks to be a BEAGLE installation issue. Try removing BEAGLE and reinstalling from https://github.com/beagle-dev/beagle-lib
