### ISSUE TITLE
Can't implement branchrate model in thorney beast

### ISSUE THREAD

**Issue by joelnitta** [beast-dev/beast-mcmc#1134]
This is in regards to a question I had originally asked @jtmccr1 about via email. I am trying to modify the [XML file](http://beast.community/tutorials/thorney_beast/files/1K_SARS-CoV-2_SG-thorney.xml) in the thorney beast [tutorial](http://beast.community/thorney_beast) to use a branchrate model (not a fixed clock; similar question to https://github.com/COG-UK/UK-lineage-dynamics-analysis/issues/10).

I have replaced the `thorneyTreeLikelihood` section in the XML, which originally appears as:

```
	<thorneyTreeLikelihood id="treeLikelihood">
		<constrainedTreeModel idref="treeModel"/>
		
		<strictClockBranchLengthLikelihood id="branchLengthLikelihood" scale="29903.0">
			<parameter id="clock.rate" value="0.00075" lower="0.0"/>
		</strictClockBranchLengthLikelihood>
		
		<constrainedBranchLengthProvider scale="29903.0">
			<constrainedTreeModel idref="treeModel"/>
			<dataTree>
				<tree idref="dataTree"/>
			</dataTree>
		</constrainedBranchLengthProvider>
	</thorneyTreeLikelihood>
```

with the following (as recommended by @jtmccr1):

```
    <thorneyTreeLikelihood id="treeLikelihood">
		<constrainedTreeModel idref="treeModel"/>
		
			<!-- The strict clock (Uniform rates across branches)                        -->
		<strictClockBranchRates id="branchRates">
			<rate>
				<parameter id="clock.rate" value="0.0001" lower="0.0"/>
			</rate>
		</strictClockBranchRates>
		
		<branchLengthLikelihood id="branchLengthLikelihood" scale="29903.0"/>
			
		<constrainedBranchLengthProvider scale="29903.0" discrete="true" minBranchlength="0.0">
			<constrainedTreeModel idref="treeModel"/>
			<dataTree>
				<tree idref="dataTree"/>
			</dataTree>
		</constrainedBranchLengthProvider>
	</thorneyTreeLikelihood>
```

However, I get an error:

```
root@41e47d631afc:/wd# beast 1K_SARS-CoV-2_SG-thorney_relaxed.xml 

        BEAST v1.10.5 Prerelease #16d1c75, 2002-2019
       Bayesian Evolutionary Analysis Sampling Trees
                 Designed and developed by
   Alexei J. Drummond, Andrew Rambaut and Marc A. Suchard
                              
               Department of Computer Science
                   University of Auckland
                  alexei@cs.auckland.ac.nz
                              
             Institute of Evolutionary Biology
                  University of Edinburgh
                     a.rambaut@ed.ac.uk
                              
              David Geffen School of Medicine
           University of California, Los Angeles
                     msuchard@ucla.edu
                              
                Downloads, Help & Resources:
                        http://beast.community
                              
Source code distributed under the GNU Lesser General Public License:
                http://github.com/beast-dev/beast-mcmc
                              
                     BEAST developers:
        Alex Alekseyenko, Guy Baele, Trevor Bedford, Filip Bielejec, Erik Bloomquist, Matthew Hall,
        Joseph Heled, Sebastian Hoehna, Denise Kuehnert, Philippe Lemey, Wai Lok Sibon Li,
        Gerton Lunter, Sidney Markowitz, Vladimir Minin, Michael Defoin Platel,
                Oliver Pybus, Chieh-Hsi Wu, Walter Xie
                              
                         Thanks to:
        Roald Forsberg, Beth Shapiro and Korbinian Strimmer

Using BEAGLE library v4.0.0 (PRE-RELEASE) for accelerated, parallel likelihood evaluation
2009-, BEAGLE Working Group - https://beagle-dev.github.io/
Citation: Ayres et al (2019) Systematic Biology 68: 1052-1061 | doi:10.1093/sysbio/syz020


Random number seed: 1656393975649


Failed to load parser: New parser (gmrfSkygridBlockUpdateOperator) in {interface dr.inference.operators.MCMCOperator} cannot replace existing parser (gmrfSkygridBlockUpdateOperator) in {interface dr.inference.operators.MCMCOperator}
line = dr.evomodelxml.coalescent.operators.GMRFSkygridBlockUpdateOperatorParser


Failed to load parser: dr.evomodelxml.coalescent.GMRFTestLikelihoodParser
line = dr.evomodelxml.coalescent.GMRFTestLikelihoodParser



Failed to load parser: dr.inference.trace.DnDsPerSiteAnalysis
line = dr.inference.trace.DnDsPerSiteAnalysis


Failed to load parser: dr.inference.trace.CnCsPerSiteAnalysis
line = dr.inference.trace.CnCsPerSiteAnalysis


Failed to load parser: dr.inference.trace.CnCsToDnDsPerSiteAnalysis
line = dr.inference.trace.CnCsToDnDsPerSiteAnalysis

Loading additional development parsers from development_parsers.properties, which is additional set of parsers only available for development version ...


Failed to load parser: dr.evomodel.continuous.hmc.TaskPool
line = dr.evomodel.continuous.hmc.TaskPool


Failed to load parser: dr.inferencexml.operators.RepeatOperatorParser
line = dr.inferencexml.operators.RepeatOperatorParser

Parsing XML file: 1K_SARS-CoV-2_SG-thorney_relaxed.xml
  File encoding: ASCII
Looking for plugins in /wd/plugins
Using node heights.

Creating the constrained tree model based on big fast tree model, 'treeModel'
  taxon count = 1000
  tree height = 0.49771087018903776
The gmrfSkyrideLikelihood has time aware smoothing
Creating a GMRF smoothed skyride model for multiple loci (SkyGrid)
        Population sizes: 39

Using discretized relaxed clock model.
  over sampling = 1
  parametric model = logNormalDistributionModel
   rate categories = 1
Fatal exception: class dr.evomodel.treelikelihood.thorneytreelikelihood.BranchLengthLikelihoodDelegate cannot be cast to class dr.inference.model.Model (dr.evomodel.treelikelihood.thorneytreelikelihood.BranchLengthLikelihoodDelegate and dr.inference.model.Model are in unnamed module of loader 'app')
java.lang.ClassCastException: class dr.evomodel.treelikelihood.thorneytreelikelihood.BranchLengthLikelihoodDelegate cannot be cast to class dr.inference.model.Model (dr.evomodel.treelikelihood.thorneytreelikelihood.BranchLengthLikelihoodDelegate and dr.inference.model.Model are in unnamed module of loader 'app')
        at dr.evomodel.treelikelihood.thorneytreelikelihood.ThorneyTreeLikelihood.<init>(Unknown Source)
        at dr.evomodelxml.treelikelihood.thorneytreelikelihood.ThorneyTreeLikelihoodParser.parseXMLObject(Unknown Source)
        at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
        at dr.xml.XMLParser.convert(Unknown Source)
        at dr.xml.XMLParser.convert(Unknown Source)
        at dr.xml.XMLParser.parse(Unknown Source)
        at dr.app.beast.BeastMain.<init>(Unknown Source)
        at dr.app.beast.BeastMain.main(Unknown Source)
```

Also note the `Failed to load parser` warnings (see #996).

The XML file is available [here](https://gist.githubusercontent.com/joelnitta/37542782c673fa35d30f348e3d358bbe/raw/98aed35fbeb5a2158c6e5b10205c5dddbc0a6c97/1K_SARS-CoV-2_SG-thorney.xml).

Running BEAST in docker container `joelnitta/thorney_beast:0.1.1` ([github](https://github.com/joelnitta/thorney-beast-docker), [docker hub](https://hub.docker.com/r/joelnitta/thorney_beast/tags)).

**Comment by GuyBaele** [comment]
It's a parsing problem (nothing wrong with the XML change you propose in terms of syntax). Add dr.evomodelxml.treelikelihood.thorneytreelikelihood.BranchLengthLikelihoodParser
to development_parsers.properties and it should run just fine (works on my computer).

**Comment by joelnitta** [comment]
Thanks for the tip @GuyBaele.

I have not edited `development_parsers.properties` before, nor do I know where to find this. I see there is some documentation mentioning adding parsers under [Developer Notes](https://github.com/beast-dev/beast-mcmc/wiki/DeveloperNotes#developer-rules-regarding-adding-a-new-parser) in the wiki, but I have no experience with java and I'm guessing you don't expect me to modify BEAST source code.

 Can you please explain in more detail what I should change?

**Comment by jtmccr1** [comment]
The new `thorneyTreeLikelihood` above section is not correctly constructed. I expect the hmc-clock branch has a intermediate version. Moving from v.0.1.1 (the tutorial version) to v.0.1.2 we change 
```
	<thorneyTreeLikelihood id="treeLikelihood">
		<constrainedTreeModel idref="treeModel"/>
		
		<strictClockBranchLengthLikelihood id="branchLengthLikelihood" scale="29903.0">
			<parameter id="clock.rate" value="0.00075" lower="0.0"/>
		</strictClockBranchLengthLikelihood>
		
		<constrainedBranchLengthProvider scale="29903.0">
			<constrainedTreeModel idref="treeModel"/>
			<dataTree>
				<tree idref="dataTree"/>
			</dataTree>
		</constrainedBranchLengthProvider>
	</thorneyTreeLikelihood>
```
to 
```
	<!-- The strict clock (Uniform rates across branches)                        -->
	<strictClockBranchRates id="branchRates">
		<rate>
			<parameter id="clock.rate" value="0.0001" lower="0.0"/>
		</rate>
	</strictClockBranchRates>

 	<thorneyTreeLikelihood id="treeLikelihood">
		<constrainedTreeModel idref="treeModel"/>
		
                <!-- this is the main difference -->
		<poissonBranchLengthLikelihood id="branchLengthLikelihood" scale="29903.0">
    		    <strictClockBranchRates idref="branchRates"/>
		</poissonBranchLengthLikelihood>	
				
		<constrainedBranchLengthProvider scale="29903.0" discrete="true" minBranchlength="0.0">
			<constrainedTreeModel idref="treeModel"/>
			<dataTree>
				<tree idref="dataTree"/>
			</dataTree>
		</constrainedBranchLengthProvider>
	</thorneyTreeLikelihood>
```

If I make this change to the tutorial xml I can run it with the v.0.1.2 release. Let me know if the issue persists!
