### ISSUE TITLE
Fatal exception: Cannot invoke "dr.evomodel.tree.TreeModel$Node.getHeight()"

### ISSUE THREAD

**Issue by Leliana42** [beast-dev/beast-mcmc#1136]
Hello,

I'm Trying to run BEAST v1.10.4 but it terminates with an error and I get this error message  :

"Fatal exception: Cannot invoke "dr.evomodel.tree.TreeModel$Node.getHeight()" because "< local2 >.rightChild" is null
java.lang.NullPointerException: Cannot invoke "dr.evomodel.tree.TreeModel$Node.getHeight()" because "< local2 >.rightChild" is null
	at dr.evomodel.tree.TreeModel$NodeHeightBounds.getLowerLimit(Unknown Source)
	at dr.evomodel.tree.TreeModel$NodeHeightBounds.getLowerLimit(Unknown Source)
	at dr.inference.model.CompoundParameter$CompoundBounds.getLowerLimit(Unknown Source)
	at dr.inference.model.CompoundParameter$CompoundBounds.getLowerLimit(Unknown Source)
	at dr.inferencexml.operators.ScaleOperatorParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)"

I don't know what is the problem, I'm used to having poorly formed xml files but this time it seems like it isn't the same kind of error, as "dr.evomodel.tree.TreeModel$Node.getHeight()" and "<local2>.rightChild" doesn't appear in the XML file. I don't know what they are and how to fix this. (The tutorials files run normally)

Please help and thank you in advance

**Comment by xji3** [comment]
The error message suggests a missing right child of an internal node on the tree.  You might want to check the starting tree if you provided any starting tree topology.  You could also share a xml file that could replicate this error (where you could replace the real sequences with fake ones if that is a concern) so that I could take a look.

**Comment by rambaut** [comment]
Without an XML it is not possible to investigate this issue.
