### ISSUE TITLE
Exception in thread "Thread-0" java.lang.RuntimeException: An error was encountered. Terminating BEAST

### ISSUE THREAD

**Issue by ypchan** [beast-dev/beast-mcmc#1163]
Dear authors,

I am running beast v1.10.4 Prerelease #bc6cbd9, but it stop with a error:
```
Exception in thread "Thread-0" java.lang.RuntimeException: An error was encountered. Terminating BEAST
	at dr.util.ErrorLogHandler.publish(Unknown Source)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
	at java.logging/java.util.logging.Logger.log(Logger.java:1029)
	at java.logging/java.util.logging.Logger.severe(Logger.java:1776)
	at dr.inference.markovchain.MarkovChain.runChain(Unknown Source)
	at dr.inference.mcmc.MCMC.chain(Unknown Source)
	at dr.inference.mcmc.MCMC.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:829)
0.908 seconds

```
I checked the XML file, and it is ok. I don't know how to bug this. I attached the xml file.
[relaxed_clock.xml.txt](https://github.com/beast-dev/beast-mcmc/files/13314921/relaxed_clock.xml.txt)

Kind regards,
Yanpeng

**Comment by xji3** [comment]
@ypchan Hi Yanpeng, I couldn't replicate your error, the xml just runs fine on my machine.  Could you please provide more details about your setup, for example, operating system, java version, beagle version and if you are running BEAST from command line?
