### ISSUE TITLE
How do I turn opt out of beagle?

### ISSUE THREAD

**Issue by jacklo225** [beast-dev/beast-mcmc#1199]
Hi,
I'm trying to directly run beast on one of the test files (testRandomLocalClock.xml) from inside Eclipse but I don't have beagle and an exception crashes the program. There is the "-beagle" flag, but it doesn't seem to do anything, or at least I can't figure out how to use it to turn off using beagle. Thanks!

```
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path: /Users/jacklo/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treelikelihood.BeagleTreeLikelihood.<init>(BeagleTreeLikelihood.java:398)
	at dr.evomodelxml.treelikelihood.BeagleTreeLikelihoodParser.createTreeLikelihood(BeagleTreeLikelihoodParser.java:86)
	at dr.evomodelxml.treelikelihood.BeagleTreeLikelihoodParser.parseXMLObject(BeagleTreeLikelihoodParser.java:176)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(AbstractXMLObjectParser.java:138)
	at dr.xml.XMLParser.convert(XMLParser.java:328)
	at dr.xml.XMLParser.convert(XMLParser.java:299)
	at dr.xml.XMLParser.parse(XMLParser.java:179)
	at dr.app.beast.BeastMain.<init>(BeastMain.java:179)
	at dr.app.beast.BeastMain.main(BeastMain.java:982)
```

**Comment by rambaut** [comment]
To calculate the likelihood of a tree, BEAST requires BEAGLE.
