### ISSUE TITLE
Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "dr.evolution.tree.NodeRef.getNumber()" because "<parameter1>" is null

### ISSUE THREAD

**Issue by AlbertoA3** [beast-dev/beast-mcmc#1210]
Dear authors, currently I try to running a throney-BEAST analysis using a lognormal Uncorrelated relax clock model, GTR substitution model and Bayesian skygrid tree prior, I used has template the thorney-xml file for strict clock model to develop my xml file.

however when i try to run my project this error message appear: 
# BEAST v1.10.5 Prerelease #a6fb
# Generated Fri Dec 06 12:53:42 CST 2024 [seed=1733511222344]
# -overwrite -beagle_CPU Modified-AY.3-RD1-URC.xml
# keywords: skygrid
state	Joint       	Prior       	Likelihood  	age(root)   	ucld.mean   
0	-2414.2022  	-203.1243   	-2211.0780  	2021.46     	1E-2        	-
Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "dr.evolution.tree.NodeRef.getNumber()" because "<parameter1>" is null
	at dr.evomodel.treelikelihood.thorneytreelikelihood.ConstrainedTreeModel.isRoot(Unknown Source)
	at dr.evomodel.tree.RateCovarianceStatistic.getStatisticValue(Unknown Source)
	at dr.inference.model.Statistic$Abstract$StatisticColumn.getDoubleValue(Unknown Source)
	at dr.inference.loggers.NumberColumn.getFormattedValue(Unknown Source)
	at dr.inference.loggers.LogColumn$Abstract.getFormatted(Unknown Source)
	at dr.inference.loggers.MCLogger.getColumnFormatted(Unknown Source)
	at dr.inference.loggers.MCLogger.log(Unknown Source)
	at dr.inference.mcmc.MCMC$2.currentState(Unknown Source)
	at dr.inference.markovchain.MarkovChain.fireCurrentModel(Unknown Source)
	at dr.inference.markovchain.MarkovChain.runChain(Unknown Source)
	at dr.inference.mcmc.MCMC.chain(Unknown Source)
	at dr.inference.mcmc.MCMC.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:1570)

I used the BEASTv1.10.5pre_thorney_0.1.2 software version, currently I use a Mac computer with M3 chip

Thank you for your time, I hope you can bring any answer, right know Im very stock in this part.
Best regards

**Comment by jtmccr1** [comment]
Hello, 

I've not seen this error before, but there are likely some xml issues. These analyses do not require a standard substitution model (GTR). I expect the next release (soon) will include beauti  support. That feature exists in a development branch at that moment. In the mean time if you are able to send me the xml I'd be happy to take a look. 

-JT

**Comment by AlbertoA3** [comment]
Many thanks for the help, I attach my file (in .txt format) to this message, hope you can find the error on my file, best regards
[Modified-AY.3-RD1-URC.txt](https://github.com/user-attachments/files/18096912/Modified-AY.3-RD1-URC.txt)

**Comment by jtmccr1** [comment]
[Modified-AY.3-RD1-URC-jtm.txt](https://github.com/user-attachments/files/18100216/Modified-AY.3-RD1-URC-jtm.txt)
this should work.

I think the error was coming from some of the covariance stats which assume a different internal tree structure in this version. There were some tree operators that don't play nicely with the constrained analysis, and would have throw and error as well.

**Comment by AlbertoA3** [comment]
Many thanks for the help, the file run correctly
