### ISSUE TITLE
4 taxa were in the xml file but error messages of "Tree with fewer than 3 taxa" by BEAST

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#764]
Originally reported on Google Code with ID 759
```
What steps will reproduce the problem?
1. 4 fasta file, each having 190KB nucldotide
2. Run BEATUi 1.8.1
3. Run BEAST 1.8.1

What is the expected output? What do you see instead?

Running was terminated with error messages

What version of the product are you using? On what operating system?
Windows BEAST 1.8.1

Please provide any additional information below.

dr.xml.XMLParseException: Error parsing '<wideExchange>' element with id, 'null':
Tree with fewer than 3 taxa
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
Feb 19, 2015 8:36:06 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, e1.hap.01.xml:
Error parsing '<wideExchange>' element with id, 'null':
Tree with fewer than 3 taxa
java.lang.RuntimeException: Terminate
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

BEAST has terminated with an error. Please select QUIT from the menu. 

```

Reported by `jml.chgr` on 2015-02-20 02:04:12

**Comment by rambaut** [comment]
Until this can be replicated with an example XML, closing.
