### ISSUE TITLE
Spurious <coalescentEventsStatistic> block inserted in log when selecting skygrid

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#767]
Originally reported on Google Code with ID 762
```
What steps will reproduce the problem?
1. svn up && ant (aka, compile from trunk) 
2. go through BEAUti and select the skygrid coalescent prior
3. If you try to run the generated XML you'll get something like:
"
Exactly one ELEMENT of type CoalescentIntervalProvider REQUIRED
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
Apr 03, 2015 3:16:04 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, Dengue4.env_testskygrid.xml:
The '<coalescentEventsStatistic>' element with id, 'null', is incorrectly constructed.
The following was expected:
Exactly one ELEMENT of type CoalescentIntervalProvider REQUIRED
java.lang.RuntimeException: Terminate
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
"
The reason seems to be an empty block:
      <coalescentEventsStatistic>
      </coalescentEventsStatistic>

that is created and inserted in the log block.

```

Reported by `luizepidemiologia` on 2015-04-03 14:22:14

**Comment by rambaut** [comment]
Was fixed by Guy in May.
