### ISSUE TITLE
Debug dump doesn't work with designMatrix

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#776]
Upon trying to store the dump file (here scheduled at the 500th iteration), BEAST throws an error and exits. Steps to reproduce: create a glmModel that contains a designMatrix and try to write a dump file. The following error will be generated:
# BEAST v1.8.3 Prerelease r20150808
# Generated Fri Aug 28 14:46:01 CEST 2015 [seed=666]

state   Posterior       Prior           Likelihood      patient0001.rootHeight  
0   -112763.4866    -4026.1384      -108737.3482    2493.52         5049.69  
100 -111562.9411    -3427.9727      -108134.9684    2493.52         5049.69  
200 -110454.2734    -3429.5087      -107024.7647    2493.52         5049.69  
300 -108744.6959    -3417.9026      -105326.7933    2171.27         5049.69  
400 -108013.8926    -3435.4177      -104578.4750    2171.27         5049.69  
Exception in thread "Thread-1" java.lang.RuntimeException: Univariate value from a design matrix
    at dr.inference.model.DesignMatrix.getParameterValue(DesignMatrix.java:72)
    at dr.inference.mcmc.DebugUtils.writeStateToFile(DebugUtils.java:87)
    at dr.inference.mcmc.DebugChainListener.currentState(DebugChainListener.java:65)
    at dr.inference.markovchain.MarkovChain.fireCurrentModel(MarkovChain.java:606)
    at dr.inference.markovchain.MarkovChain.runChain(MarkovChain.java:186)
    at dr.inference.mcmc.MCMC.chain(MCMC.java:292)
    at dr.inference.mcmc.MCMC.run(MCMC.java:212)
    at java.lang.Thread.run(Thread.java:745)

**Comment by rambaut** [comment]
@GuyBaele - status of this bug?

**Comment by GuyBaele** [comment]
Tried it with a joint inference GLM XML from the Ebola repository and worked fine.
