### ISSUE TITLE
v1.8.3 - parsing error between ancestralTreeLikelihood and CP1+2.treeLikelihood?

### ISSUE THREAD

**Issue by mmelendrez** [beast-dev/beast-mcmc#788]
Just recently updated to version 1.8.3 and an XML
![8 ha_beast_e_phylogeo_strict xml](https://cloud.githubusercontent.com/assets/2855130/12304025/7f87ea44-b9fb-11e5-9d1e-1e915477e1c3.png)

 file that previously ran fine with beast v1.8.0 is now giving me the following error:
```
[melanie.melendrez@amedwrair015380 Phylogeography]$ beast -beagle_sse -threads 0 8.HA_BEAST_E_phylogeo_strict.xml 

        BEAST v1.8.3 Prerelease r20160103, 2002-2016
       Bayesian Evolutionary Analysis Sampling Trees
                 Designed and developed by
   Alexei J. Drummond, Andrew Rambaut and Marc A. Suchard
                              
               Department of Computer Science
                   University of Auckland
                  alexei@cs.auckland.ac.nz
                              
             Institute of Evolutionary Biology
                  University of Edinburgh
                     a.rambaut@ed.ac.uk
                              
              David Geffen School of Medicine
           University of California, Los Angeles
                     msuchard@ucla.edu
                              
                Downloads, Help & Resources:
                 	http://beast.bio.ed.ac.uk
                              
Source code distributed under the GNU Lesser General Public License:
          	http://github.com/beast-dev/beast-mcmc
                              
                     BEAST developers:
	Alex Alekseyenko, Guy Baele, Trevor Bedford, Filip Bielejec, Erik Bloomquist, Matthew Hall,
	Joseph Heled, Sebastian Hoehna, Denise Kuehnert, Philippe Lemey, Wai Lok Sibon Li,
	Gerton Lunter, Sidney Markowitz, Vladimir Minin, Michael Defoin Platel,
          	Oliver Pybus, Chieh-Hsi Wu, Walter Xie
                              
                         Thanks to:
    	Roald Forsberg, Beth Shapiro and Korbinian Strimmer

Using BEAGLE library v2.1.2 for accelerated, parallel likelihood evaluation
2009-2013, BEAGLE Working Group - http://beagle-lib.googlecode.com/
Citation: Ayres et al (2012) Systematic Biology 61: 170-173 | doi:10.1093/sysbio/syr100



Random number seed: 1452710199313


Failed to load parser: dr.inferencexml.trace.GeneralizedHarmonicMeanAnalysisParser
line = dr.inferencexml.trace.GeneralizedHarmonicMeanAnalysisParser

Failed to install parser: New parser (dirichletPrior) in {interface dr.inference.model.Likelihood} cannot replace existing parser (dirichletPrior) in {class dr.inference.distribution.MultivariateDistributionLikelihood}


Loading additional development parsers from development_parsers.properties, which is additional set of parsers only available for development version ...


Failed to load parser: dr.evomodel.treelikelihood.RootDiscreteStateStatistic
line = dr.evomodel.treelikelihood.RootDiscreteStateStatistic

WARNING: parser - dr.app.beagle.multidimensionalscaling.MultiDimensionalScalingLikelihood in development_parsers.properties is duplicated, which is REPLACING the same parser loaded previously.

Parsing XML file: 8.HA_BEAST_E_phylogeo_strict.xml
  File encoding: UTF8
Looking for plugins in /media/VD_Research/Analysis/ProjectBased_Analysis/melanie/share/Issue_10712/BEASTE/Phylogeography/plugins
Read alignment: alignment
  Sequences = 388
      Sites = 1701
   Datatype = nucleotide
Site patterns 'CP1+2.patterns' created by merging 2 pattern lists
  pattern count = 212
Site patterns 'CP3.patterns' created from positions 3-1701 of alignment 'alignment'
  only using every 3 site
  pattern count = 567
Read attribute patterns, 'Region.pattern' for attribute, Region
Creating the tree model, 'treeModel'
  initial tree topology = ((((((((((((((((((((((A_Boston_YGA_01170_2013,A_Suzhou_1275_2013),Maroon_A_Boston_YGA_00004_2012),Lblue_A_Peru_PER358_2012),(Dred_A_Boston_YGA_01086_2012,Lblue_43_Japan_2_5_2012)),FLU_PMKA1561_Thailand_8_25_2011),((Dblue_F089_Kuwait_01_2014,Maroon_A_Chicago_YGA_04188_2013),Lblue_A_Singapore_H2011_504C_2011)),(Lblue_A_Peru_PER363_2012,Maroon_A_Boston_YGA_01038_2012)),A_Peru_PER065_2010),((((((((A_Boston_YGA_02053_2013,Dblue_F146_Kuwait_02_2014),1514A06505401N_Kosovo_2_6_2013),Lblue_32_USA_2_29_2012),(Dblue_F142_Kuwait_02_2014,Maroon_A_Chicago_YGA_04198_2013)),(A_Boston_DOA2_133_2012,A_Boston_DOA2_199_2013)),(Dred_A_Peru_PER353_2012,Lblue_A_Stockholm_12_2012)),A_Boston_DOA2_136_2012),A_Singapore_H2011_751_2011)),((((((((A_Boston_YGA_01112_2013,Dblue_A_Victoria_505_2013),Maroon_A_Boston_YGA_02005_2012),A_Boston_DOA38_2011),(A_Boston_YGA_01040_2012,Maroon_A_Santa_Clara_YGA_03075_2013)),((Lblue_20_USA_2_8_2012,Lblue_A_Michigan_03_2012),Lblue_FDX21045_USA_2012)),(((A_Boston_DOA41_2011,Lblue_A_Peru_PER028_2011),A_Shanghai_Fengxian_1170_2011),A_Tennessee_F2019_2011)),Lblue_A_Peru_PER307_2011),(((((Maroon_A_Boston_DOA2_145_2013,Maroon_A_Boston_YGA_01139_2013),A_Boston_YGA_01027_2012),(Lblue_A_Peru_PER301_2012,Maroon_A_Chicago_YGA_04120_2012)),(A_Boston_YGA_01107_2012,Maroon_A_Texas_JMM_59_2012)),A_Peru_PER207_2010))),(((((((A_Boston_YGA_01145_2013,A_Santa_Clara_YGA_03077_2013),Lblue_45_SouthKorea_1_13_2012),Dred_A_Peru_PER051_2012),(A_Boston_DOA09_2011,Lblue_A_Peru_PER354_2012)),A_California_NHRC0001_2011),((A_Boston_DOA2_232_2013,Dblue_F072_Kuwait_01_2014),(Lblue_A_Peru_PER121_2011,Lblue_A_Utah_12_2011))),A_Boston_73_2009)),Lblue_A_Peru_PER371_2012),A_California_VRDL349_2009),((((((Maroon_A_Boston_YGA_00020_2012,Maroon_A_Chicago_YGA_04047_2012),Lblue_A_Peru_PER337_2011),A_Hong_Kong_H090_692_V12_2009),A_Boston_40_2009),(((A_New_York_3626_2009,A_Peru_PER077_2010),Lblue_A_Peru_PER092_2011),(1514A00905321T_Mexico_2_26_2013,Lblue_A_Peru_PER031_2012))),A_Boston_19_2008)),(((((((A_Singapore_C2011_422_2011,Lblue_A_Singapore_H2011_570_2011),A_Tennessee_F2031A_2011),A_Peru_PER319_2010),FLU_PHD_0142_CP2_Philippines_7_27_2009),(A_New_York_1134_2008,A_Peru_PER370_2010)),((A_Korea_AF05_2008,A_Peru_PER382_2010),A_Hiroshima_52_2005_CA04_VaccineAlt)),(((((A_Boston_YGA_01120_2013,Maroon_A_Chicago_YGA_04036_2012),A_Boston_YGA_02026_2013),Dred_A_Boston_DOA2_163_2013),(((Dred_A_Chicago_YGA_04131_2013,Lblue_A_Peru_PER187_2011),A_Boston_YGA_00055_2013),A_Beijing_Xicheng_1409_2011)),(((Dblue_A_Pennsylvania_12_2013,Dblue_F083_Kuwait_01_2014),Lblue_A_Peru_PER175_2012),Dblue_F102_Kuwait_01_2014)))),(((((((((((A_Boston_DOA2_207_2013,Maroon_A_Texas_JMM_3_2012),Lblue_A_Peru_PER359_2012),((A_Boston_DOA2_218_2013,Maroon_A_Santa_Clara_YGA_03076_2013),A_Boston_YGA_01203_2013)),Lblue_A_Peru_PER066_2011),((((Dblue_F181_3_Kuwait_02_2014,Maroon_A_Boston_DOA2_224_2013),Lblue_A_Peru_PER166_2011),A_Boston_YGA_01006_2012),Lblue_A_PHILIPPINES_3969_2011)),(A_Peru_PER176_2011,A_Peru_PER253_2010)),A_Arizona_WRAIR1562P_2009),A_Singapore_C2010_471aV_2010),((((((A_Boston_DOA2_219_2012,Lblue_39_USA_2_14_2012),Lblue_FLU_PHC_0275_Philippines_11_15_2011),Lblue_A_Peru_PER222_2012),A_Boston_YGA_01033_2012),A_Peru_PER053_2010),A_Peru_PER123_2010)),((((((((A_Peru_PER134_2011,Lblue_A_Singapore_C2011_564_2011),A_Boston_YGA_01023_2012),Maroon_A_Chicago_YGA_04086_2012),A_Peru_PER023_2010),A_Peru_PER165_2010),FLU_PMKA0967_CP3_Thailand_10_26_2010),(A_Hong_Kong_H090_710_V10_2009,A_Hong_Kong_H090_720_V10_2009)),A_Boston_88_2008)),((((((A_Peru_PER115_2011,Lblue_A_Peru_PER156_2012),A_Peru_PER034_2011),A_Boston_DOA60_2011),Lblue_A_SOUTH_AUSTRALIA_2_2013),A_Peru_PER340_2010),A_California_VRDL136_2009))),(((((((((A_Texas_JMM_58_2012,Lblue_A_NEW_CALEDONIA_1_2012),Lblue_A_Peru_PER219_2012),Maroon_A_Texas_JMM_8_2012),((Dblue_F123_Kuwait_02_2014,Lblue_FLU_AFPA_00013_Philippines_10_10_2011),A_Peru_PER328_2011)),A_California_VRDL147_2009),A_Managua_90_01_2010),(((((A_Peru_PER105_2012,A_Texas_JMM_47_2012),Lblue_FLU_PHB_0334_Philippines_11_29_2011),Lblue_A_Singapore_H2011_518_2011),A_Peru_PER174_2010),A_Managua_1784_03_2010)),((A_Peru_PER142_2011,Maroon_A_Boston_YGA_01045_2012),A_Texas_NHRC0001_2011)),((((((((Maroon_A_Chicago_YGA_04085_2012,Maroon_A_Texas_JMM_30_2012),Lblue_42_Japan_1_31_2012),Lblue_A_Peru_PER072_2012),((Lblue_A_Peru_PER326_2012,Maroon_A_Texas_JMM_1_2012),Lblue_FLU_PHB_0332_Philippines_11_22_2011)),((1514A07805419T_Hungary_2_5_2013,A_Peru_PER049_2011),Lblue_A_Peru_PER315_2010)),(((A_Boston_YGA_01115_2013,A_Mexico_City_WRAIR3579N_2010),A_Peru_PER390_2010),A_Peru_PER154_2010)),A_Santa_Clara_YGA_03046_2013),A_Mexico_24010_2008))),(((((((((((A_Boston_YGA_00044_2013,Dblue_F099_Kuwait_01_2014),A_Boston_YGA_01089_2012),A_Boston_YGA_02047_2013),(A_Boston_YGA_01025_2012,A_Santa_Clara_YGA_03067_2012)),(A_Managua_58_11_2011,Lblue_A_Singapore_C2011_647_2011)),((FPI002788_Peru_12_1_2011,Lblue_A_Rhode_Island_01_2012),Maroon_A_Boston_YGA_00015_2012)),(((A_Boston_DOA2_102_2012,A_Boston_YGA_00019_2012),Maroon_A_Boston_YGA_01111_2013),(A_Managua_5271_04_2010,Dred_FDX50085_USA_2012))),A_California_VRDL338_2009),((((((((Lblue_FLU_PHC_0291_Philippines_12_6_2011,Maroon_A_Boston_DOA2_138_2012),A_Boston_YGA_01024_2012),(Dblue_F093_Kuwait_01_2014,Dblue_F147_Kuwait_02_2014)),((A_Boston_YGA_00056_2013,Lblue_29_USA_2_17_2012),Lblue_A_Peru_PER217_2012)),((FPP00919_Peru_10_25_2011,Lblue_55121_USA_2012),Lblue_55117_USA_2012)),(((Lblue_A_Peru_PER313_2012,Lblue_A_Peru_PER331_2012),A_Boston_YGA_01036_2012),(Dblue_F075_Kuwait_01_2014,Lblue_FLU_PHC_0304_Philippines_12_20_2011))),(A_DaNang_DN453_2008,A_Peru_PER162_2010)),(((Lblue_1514A07804502N_Hungary_12_12_2011,Lblue_A_Singapore_C2011_496_2011),Maroon_A_Boston_YGA_02014_2012),A_Tennessee_F2053_2011))),A_Texas_1_1977),(A_New_York_UR07_0160_2008,Lblue_FLUEJKSV0031_Indonesia_2_1_2012))),A_Colorado_2_1986),(((((((((((((A_Chicago_YGA_04107_2012,Dred_A_Puerto_Rico_36_2012),Lblue_1514A00504950T_Russia_1_11_2012),Lblue_FPP01106_Peru_12_29_2011),Dblue_A_Washington_18_2013),A_Managua_3622_02_2010),(Lblue_A_PHILIPPINES_3948_2011,Lblue_FLUEINSV0056_India_9_12_2011)),A_Peru_PER103_2010),(((A_Boston_YGA_02004_2012,Maroon_A_Texas_JMM_43_2012),A_Hong_Kong_H090_703_V10_2009),A_Managua_4855_03_2010)),(((((((A_Chicago_YGA_04122_2012,A_Chicago_YGA_04142_2013),Lblue_A_Peru_PER343_2011),Lblue_A_Peru_PER262_2012),((Dred_A_Stockholm_42_2011,Lblue_A_Stockholm_29_2011),A_Peru_PER334_2011)),A_Peru_PER297_2010),((((Dred_A_Chicago_YGA_04134_2013,Lblue_A_Peru_PER037_2012),Lblue_A_TASMANIA_1_2012),A_Boston_DOA2_203_2012),Maroon_A_Chicago_YGA_04200_2013)),A_California_VRDL302_2009)),(((A_California_VRDL177_2009,A_California_VRDL322_2009),A_New_York_1150_2008),((Lblue_48_USA_1_9_2012,Lblue_A_Peru_PER063_2012),A_New_York_1131_2008))),(((((((((Lblue_A_Peru_PER232_2012,Maroon_A_Boston_YGA_01098_2012),A_Boston_DOA2_101_2012),(A_Boston_YGA_02058_2013,Lblue_FLU_BTA_00010_Bhutan_9_27_2011)),Lblue_A_Singapore_C2011_614_2011),(((A_Santa_Clara_YGA_03042_2013,Lblue_A_Peru_PER221_2012),Lblue_A_Peru_PER113_2012),Dblue_F124_Kuwait_02_2014)),((((A_Costa_Rica_4009_2013,Maroon_A_Boston_YGA_01125_2013),A_Victoria_506_2013),A_Boston_YGA_02054_2013),A_Boston_YGA_01047_2012)),A_California_VRDL385_2009),A_Kentucky_UR07_0068_2008),(((Lblue_17_Japan_1_31_2012,Lblue_FLU_PHC_0286_Philippines_11_29_2011),A_California_VRDL166_2009),(A_Bangladesh_5014_2009,A_California_VRDL330_2009)))),A_Bilthoven_10684_1982),((((A_Boston_YGA_01129_2013,Maroon_A_Chicago_YGA_04165_2013),(Lblue_A_Peru_PER153_2012,Lblue_A_Singapore_C2011_573_2011)),A_Nanjing_1655_2010),((Dred_A_Michigan_33_2012,Lblue_SE680_Japan_1_24_2012),Lblue_A_Singapore_C2011_452_2011)))),((((((((((((((((((A_Boston_YGA_01201_2013,A_Santa_Clara_YGA_03008_2013),A_Santa_Clara_YGA_03054_2013),A_Nicaragua_AGA2_32_2011),A_VICTORIA_103_2011),A_Boston_DOA66_2011),A_Peru_PER215_2010),A_Anhui_Baohe_1456_2010),A_Peru_PER254_2010),A_New_York_3103_2009),A_New_York_3064_2009),(((((((A_Boston_YGA_01014_2012,Maroon_A_Texas_JMM_39_2012),Maroon_A_Boston_DOA2_155_2012),A_Boston_DOA2_158_2013),A_Hunan_Beihu_1143_2011),(Dblue_F078_Kuwait_01_2014,Maroon_A_Chicago_YGA_04065_2012)),A_Singapore_C2009_803bV_2009),A_Boston_68_2008)),A_Thailand_CU_1102_2008),(((((Lblue_FLU_AFPA_00063_Philippines_1_1_2012,Maroon_A_Boston_DOA2_141_2012),A_Peru_PER097_2011),A_Hue_H207_2008),Lblue_A_Peru_PER346_2011),A_California_VRDL396_2009)),A_New_York_1190_2009),((((((Maroon_A_Boston_YGA_00016_2012,Maroon_A_Texas_JMM_35_2012),A_Chicago_YGA_04184_2013),Maroon_A_Boston_YGA_02015_2012),Lblue_A_Singapore_C2011_518_2011),Lblue_A_Peru_PER017_2011),((Lblue_A_Peru_PER197_2011,Lblue_A_Peru_PER305_2012),A_Boston_YGA_01008_2012))),((((((((((A_Boston_DOA57_2011,A_Singapore_C2010_937V_2010),(A_Peru_PER250_2010,A_Tianjin_Nankai_1842_2010)),Dblue_F167_Kuwait_03_2014),(((A_Peru_PER043_2011,Lblue_A_Peru_PER136_2011),Maroon_A_Boston_YGA_01148_2013),Maroon_A_Boston_YGA_00038_2013)),A_New_York_3272_2009),((((Lblue_SE863_Japan_2_3_2012,Maroon_A_Boston_YGA_02002_2012),A_Peru_PER135_2010),A_Boston_75_2009),A_Singapore_C2009_863_2009)),(((((A_Boston_YGA_00035_2013,Dblue_A_Utah_07_2013),Dred_A_Peru_PER102_2012),A_Boston_DOA2_240_2013),A_Peru_PER373_2010),Maroon_A_Chicago_YGA_04110_2012)),(A_Costa_Rica_4700_2013,A_New_York_3918_2009)),(((A_Hong_Kong_H090_755_V20_2009,A_Ohio_UR07_0016_2008),A_New_York_UR07_0133_2008),A_New_York_3297_2009)),((((((Dred_A_California_17_2012,Lblue_A_Peru_PER167_2012),A_Peru_PER013_2010),A_Iraq_WRAIR1244P_2009),A_Pennsylvania_PIT42_2008),A_Malaysia_1997831_2008),A_Guam_WRAIR1557P_2009))),(((((A_Boston_63_2008,A_California_VRDL354_2009),(A_California_VRDL172_2009,A_New_York_1139_2008)),A_Brisbane_10_2007_CA04_Vaccine),A_Boston_YGA_01096_2012),A_New_York_3470_2009)),((((((((((((Dred_27_USA_3_6_2012,FPU00363_Peru_12_19_2011),(Lblue_A_Washington_16_2012,Lblue_FLUEJKSV0033_Indonesia_2_13_2012)),Lblue_A_SOUTH_AUSTRALIA_313_2011),Lblue_A_Peru_PER014_2011),(((A_Boston_YGA_01061_2012,Lblue_A_Peru_PER309_2012),(Dred_25_USA_3_5_2012,Lblue_A_Peru_PER042_2012)),(A_Chicago_YGA_04064_2012,Lblue_IPE00830_Peru_1_10_2012))),((Dblue_F074_Kuwait_01_2014,Maroon_A_Alaska_02_2013),Lblue_A_Ohio_02_2012)),((((A_Santa_Clara_YGA_03050_2013,Lblue_A_Thailand_VIROAF2_2012),Maroon_A_Boston_YGA_01157_2013),(A_Boston_YGA_01065_2012,A_PERTH_41_2012)),((Lblue_A_Peru_PER209_2012,Maroon_A_Chicago_YGA_04124_2012),FLUEBMSV00004_Burma_9_21_2011))),Maroon_A_Boston_YGA_01026_2012),A_Hong_Kong_H090_692_V10_2009),A_Finland_97_2009),(((((Lblue_A_Peru_PER280_2012,Lblue_FDX21048_USA_2012),Lblue_FLU_PHC_0284_Philippines_11_29_2011),Lblue_A_Peru_PER117_2012),Lblue_A_Boston_YGA_00046_2013),(A_Boston_YGA_01015_2012,Lblue_A_Peru_PER216_2012))),A_Shanghai_11_1987))),A_Caen_1_1984)
  tree height = 96.60592985925092
The gmrfSkyrideLikelihood has time aware smoothing
Creating a GMRF smoothed skyride model:
	Population sizes: 387
	If you publish results using this model, please reference: Minin, Bloomquist and Suchard (2008) Molecular Biology and Evolution, 25, 1459-1471.
Using strict molecular clock model.
Using strict molecular clock model.
Creating state frequencies model 'frequencies': Initial frequencies = {0.25, 0.25, 0.25, 0.25}
Creating HKY substitution model. Initial kappa = 2.0
Creating state frequencies model 'frequencies': Initial frequencies = {0.25, 0.25, 0.25, 0.25}
Creating HKY substitution model. Initial kappa = 2.0
Creating site model: 
  with initial relative rate = 0.5
  4 category discrete gamma with initial shape = 0.5
Creating site model: 
  with initial relative rate = 0.5
  4 category discrete gamma with initial shape = 0.5
dr.xml.XMLParseException: Error parsing '<ancestralTreeLikelihood>' element with id, 'CP1+2.treeLikelihood':
Ancestral state reconstruction cannot be used with compressed (unique) patterns.
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
Jan 13, 2016 1:36:41 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, 8.HA_BEAST_E_phylogeo_strict.xml:
Error parsing '<ancestralTreeLikelihood>' element with id, 'CP1+2.treeLikelihood':
Ancestral state reconstruction cannot be used with compressed (unique) patterns.
java.lang.RuntimeException: Terminate
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
```

Suggestions?

I uploaded my XML - just remove the .png

**Comment by rambaut** [comment]
This isn't a bug, but a check I added very recently to prevent the use of ancestral state reconstruction on compressed patterns (because the ancestral reconstructions won't be correct). 

In the above file, why is the sequence likelihood using 'ancestralTreeLikelihood'? Are you trying to reconstruct the ancestral sequences? If not, then changing 'ancestralTreeLikelihood' to 'treeLikelihood' (for the sequences) should fix this.

**Comment by mmelendrez** [comment]
Ah OK. I can make that change. No I was just reconstructing ancestral
states for my traits not the sequences.
