### ISSUE TITLE
Concurrency error when using Markov Jumps on multiple partitions

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#792]
Example with the attached XML. Seems to need 3 MarkovJumpTreeLikelihoods to get this error. This has 2 sequence partitions and a location trait.

java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 5
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at dr.inference.model.CompoundLikelihood.getLogLikelihood(CompoundLikelihood.java:211)
	at dr.inference.model.CompoundLikelihood.evaluateLikelihoods(CompoundLikelihood.java:241)
	at dr.inference.model.CompoundLikelihood.getLogLikelihood(CompoundLikelihood.java:204)
	at dr.inference.markovchain.MarkovChain.evaluate(MarkovChain.java:485)
	at dr.inference.markovchain.MarkovChain.<init>(MarkovChain.java:101)
	at dr.inference.mcmc.MCMC.init(MCMC.java:147)
	at dr.inference.mcmc.MCMC.init(MCMC.java:101)
	at dr.inferencexml.MCMCParser.parseXMLObject(MCMCParser.java:138)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(AbstractXMLObjectParser.java:119)
	at dr.xml.XMLParser.convert(XMLParser.java:317)
	at dr.xml.XMLParser.convert(XMLParser.java:288)
	at dr.xml.XMLParser.parse(XMLParser.java:167)
	at dr.app.beast.BeastMain.<init>(BeastMain.java:153)
	at dr.app.beast.BeastMain.main(BeastMain.java:758)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
	at dr.inference.model.CompoundLikelihood$LikelihoodCaller.call(CompoundLikelihood.java:505)
	at dr.inference.model.CompoundLikelihood$LikelihoodCaller.call(CompoundLikelihood.java:491)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[concurrencyError.xml.zip](https://github.com/beast-dev/beast-mcmc/files/132559/concurrencyError.xml.zip)

**Comment by rambaut** [comment]
This error is the result of having the same likelihood element reference multiple times. This happens due to a bug in the generation code from BEAUti where the branchRatesModel reference gets repeated.

**Comment by rambaut** [comment]
Implemented a check in BEAST to ensure the same likelihood element is not inserted multiple times into the likelihood (this is always likely to be unintended).
