### ISSUE TITLE
Skygrid can't cope with trees of size 2

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#795]
If skygrid has a locus with a tree of size 2 it throws an array out of bounds:

Fatal exception: 3
java.lang.ArrayIndexOutOfBoundsException: 3
    at dr.evolution.coalescent.TreeIntervals.getIntervalTime(TreeIntervals.java:340)
    at dr.evomodel.coalescent.GMRFMultilocusSkyrideLikelihood.setupSufficientStatistics(GMRFMultilocusSkyrideLikelihood.java:383)
    at dr.evomodel.coalescent.GMRFMultilocusSkyrideLikelihood.<init>(GMRFMultilocusSkyrideLikelihood.java:152)
    at dr.evomodelxml.coalescent.GMRFSkyrideLikelihoodParser.parseXMLObject(GMRFSkyrideLikelihoodParser.java:199)

Probably an issue in the loop over times in GMRFMultilocusSkyrideLikelihood.setupSufficientStatistics() for this edge situation.

**Comment by msuchard** [comment]
Might you be able to provide an XML?  I just tried to create my own 2-taxon XML and it ran without error.

**Comment by rambaut** [comment]
OK. It looks like this is more complex than I thought. Kicking it into the long grass until I can come up with a nice example.
