### ISSUE TITLE
BEAST produces error with ANT build

### ISSUE THREAD

**Issue by mtolkoff** [beast-dev/beast-mcmc#845]
It works in intellij, but when I try to use ant to build the latest version and run it on the command line I get this error:

`Exception in thread "main" java.lang.NoClassDefFoundError: dr/evomodel/treedatalikelihood/TreeDataLikelihood
	at dr.evomodel.operators.PrecisionMatrixGibbsOperator$1.<init>(Unknown Source)
	at dr.evomodel.operators.PrecisionMatrixGibbsOperator.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at dr.app.beast.BeastParser.loadProperties(Unknown Source)
	at dr.app.beast.BeastParser.<init>(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: dr.evomodel.treedatalikelihood.TreeDataLikelihood
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
`

The class looks like it should be loaded properly in PrecisionMatrixGibbsOperator. @msuchard was the last person updating this. Any ideas?

**Comment by msuchard** [comment]
Pre-release build.xml fixed in af6bcd4b913121c9aa2974fbb23670c4401e724a
