### ISSUE TITLE
Newton-Raphson error

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#875]
When running the [attached](https://github.com/beast-dev/beast-mcmc/files/825235/Dengue4env_stl_0.30.xml.txt) XML with seed `666`, one gets 
```
Exception in thread "Thread-1" java.lang.RuntimeException: Newton Raphson algorithm did not converge within 200 step to a norm less than 0.01
Try starting BEAST with a more accurate initial tree.
	at dr.evomodel.coalescent.operators.GMRFMultilocusSkyrideBlockUpdateOperator.newNewtonRaphson(Unknown Source)
	at dr.evomodel.coalescent.operators.GMRFMultilocusSkyrideBlockUpdateOperator.newtonRaphson(Unknown Source)
	at dr.evomodel.coalescent.operators.GMRFMultilocusSkyrideBlockUpdateOperator.doOperation(Unknown Source)
	at dr.inference.operators.SimpleMCMCOperator.operate(Unknown Source)
	at dr.inference.markovchain.MarkovChain.runChain(Unknown Source)
	at dr.inference.mcmc.MCMC.chain(Unknown Source)
	at dr.inference.mcmc.MCMC.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

Here's the tail of the log just before that happens:
```
1902000	-4954.0803  	-1208.3671  	-3745.7132  	2.49075E27  	2.29426E-29 	0.11 hours/million states
1903000	-4963.8089  	-1211.0020  	-3752.8068  	3.0162E27   	1.40248E-29 	0.11 hours/million states
1904000	-4920.6730  	-1178.8707  	-3741.8023  	1.15356E27  	4.28443E-29 	0.11 hours/million states
1905000	-4928.0656  	-1190.9160  	-3737.1496  	9.04579E26  	6.59756E-29 	0.11 hours/million states
```
So the rate is going to zero and hence the root is growing larger. This shouldn't cause problems, however. Not sure what's going on, could be something crazy in my XML...

**Comment by alexeid** [comment]
Numerical errors are more likely with very large or very small numbers going in to subsequent calculations. Is this a data set that is calibrated to allow separate estimate of rate and root height? It looks like there is some non-identifiability problem between those two parameters in this analysis.

Alexei

**Comment by maxbiostat** [comment]
hey @alexeid,

This is just plain old dengue 4 (env) data set, with dated tips. The only "extraneous" thing in the analysis is our new kernel, I guess, but the error is unrelated.

**Comment by rambaut** [comment]
`		<cutOff>
			<parameter id="skygrid.cutOff" value="380.0"/>
		</cutOff>
`

This is way off for this data set.  Try 80.

**Comment by maxbiostat** [comment]
I didn't set that. BEAUti did. make of this what you will, but this error does not seem like good behaviour to me.

**Comment by rambaut** [comment]
Pushing this to #899 which has a nice quickly occurring example XML.
