### ISSUE TITLE
random walk window size cannot be negative -- SubTreeJump

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#877]
@rambaut , when running the [attached XML](https://github.com/beast-dev/beast-mcmc/files/862113/DS1_STJ.xml.txt) with
```bash
$ java -Xmx4096m -Djava.library.path=/home/max/lib -cp /home/max/BEASTv1.8.4/lib/beast.jar dr.app.beast.BeastMC -overwrite DS1_STJ.xml
```
I get (the tail):
```
-6631.0277  [-6595.672] -6626.5583  
9998000 -6595.6720      21.8913         -6617.5633      4.92125E-2      0.29 hours/million states
-6634.4373  [-6604.4632] -6633.6389  
9999000 -6604.4632      20.7430         -6625.2062      5.40243E-2      0.29 hours/million states

Time taken: 2.882948611111111 hours

Operator analysis
Operator                              Pr(accept)  Performance suggestion
scale(kappa)                  0.613   0.2339      good
frequencies                   0.048   0.2346      good
scale(alpha)                  0.423   0.2341      good
Exception in thread "Thread-1" java.lang.IllegalArgumentException: random walk window size cannot be negative: -58404.38968167876
        at dr.inference.operators.OperatorUtils.optimizeWindowSize(Unknown Source)
        at dr.evomodel.operators.SubtreeJumpOperator.getPerformanceSuggestion(Unknown Source)
        at dr.inference.mcmcmc.MCMCMC.finish(Unknown Source)
        at dr.inference.mcmcmc.MCMCMC.run(Unknown Source)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
```

Note: I can't get it to run without the `overwrite` flag, otherwise BEAST complains about overwriting log files.

**Comment by rambaut** [comment]
I can't replicate this. I think it might happen when the bias is set to 0.0 but auto optimization is off (which I should fix). But I also don't recognize the main class in the command line above 'dr.app.beast.BeastMC'.

**Comment by maxbiostat** [comment]
This was an MC³ run. At some point I'll come back to MC³ testing and we'll find out whether there was a problem.

**Comment by rambaut** [comment]
Don't bother. I have put a check in for a zero or negative bias which will stop the error coming up but it is an extreme edge case.
