### ISSUE TITLE
Skygrid throws Newton-Raphson error even with reasonable starting values

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#899]
if one runs [this](https://github.com/beast-dev/beast-mcmc/files/1074386/Dengue4.env_vanilla.xml.txt) XML with ```beast-dev -seed 666 -threads 1``` one gets

```bash
# BEAST v1.9.0pre20170207 Prerelease #20fe946
# Generated Wed Jun 14 12:12:38 BST 2017 [seed=666]
# -beagle_SSE -seed 666 -threads 1 Dengue4.env_vanilla.xml
state	Posterior   	Prior       	Likelihood  	rootAge     	ucld.mean   
0	-22178.9502 	-1440.1547  	-20738.7955 	1936.00     	1.00000     	-
1000	-8567.2802  	-405.2073   	-8162.0729  	1947.06     	0.27465     	-
2000	-5799.6373  	-367.5387   	-5432.0986  	1953.91     	5.23059E-2  	-
Exception in thread "Thread-1" java.lang.RuntimeException: Newton Raphson algorithm did not converge within 200 step to a norm less than 0.01
Try starting BEAST with a more accurate initial tree.
	at dr.evomodel.coalescent.operators.GMRFMultilocusSkyrideBlockUpdateOperator.newNewtonRaphson(Unknown Source)
	at dr.evomodel.coalescent.operators.GMRFMultilocusSkyrideBlockUpdateOperator.newtonRaphson(Unknown Source)
	at dr.evomodel.coalescent.operators.GMRFMultilocusSkyrideBlockUpdateOperator.doOperation(Unknown Source)
	at dr.inference.operators.SimpleMCMCOperator.operate(Unknown Source)
	at dr.inference.markovchain.MarkovChain.runChain(Unknown Source)
	at dr.inference.mcmc.MCMC.chain(Unknown Source)
	at dr.inference.mcmc.MCMC.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
2.934 seconds
````
This is connected to #875,  #888 and #746 but imho somewhat different because starting values for logPopSizes are reasonable.

**Comment by maxbiostat** [comment]
To reproduce this error, one must do `wget https://github.com/beast-dev/beast-mcmc/archive/46ca0687ef9ede34cafeca8721c1fe52b0e95547.zip`, extract an compile (`ant`). This gets a snapshot of the repo roundabout the time this was reported.

**Comment by rambaut** [comment]
Related to #1030 - closing
