### ISSUE TITLE
Problem with LogNormalDistributionModel prevents from running standard XML files

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#924]
The following XML, which used to run fine, now gives the following error:

java.lang.NullPointerException
	at dr.inference.distribution.LogNormalDistributionModel.getMu(LogNormalDistributionModel.java:194)
	at dr.inference.distribution.LogNormalDistributionModel.quantile(LogNormalDistributionModel.java:333)
	at dr.evomodel.branchratemodel.DiscretizedBranchRates.setupRates(DiscretizedBranchRates.java:339)
	at dr.evomodel.branchratemodel.DiscretizedBranchRates.getBranchRate(DiscretizedBranchRates.java:304)
	at dr.evomodel.treelikelihood.BeagleTreeLikelihood.traverse(BeagleTreeLikelihood.java:1143)
	at dr.evomodel.treelikelihood.BeagleTreeLikelihood.traverse(BeagleTreeLikelihood.java:1171)
	at dr.evomodel.treelikelihood.BeagleTreeLikelihood.calculateLogLikelihood(BeagleTreeLikelihood.java:874)
	at dr.evomodel.treelikelihood.AbstractTreeLikelihood.getLogLikelihood(AbstractTreeLikelihood.java:184)
	at dr.inference.model.CompoundLikelihood.evaluateLikelihoods(CompoundLikelihood.java:240)
	at dr.inference.model.CompoundLikelihood.getLogLikelihood(CompoundLikelihood.java:203)
	at dr.inference.model.CompoundLikelihood.evaluateLikelihoods(CompoundLikelihood.java:240)
	at dr.inference.model.CompoundLikelihood.getLogLikelihood(CompoundLikelihood.java:203)
	at dr.inference.markovchain.MarkovChain.evaluate(MarkovChain.java:474)
	at dr.inference.markovchain.MarkovChain.<init>(MarkovChain.java:97)
	at dr.inference.mcmc.MCMC.init(MCMC.java:81)
	at dr.inferencexml.MCMCParser.parseXMLObject(MCMCParser.java:139)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(AbstractXMLObjectParser.java:136)
	at dr.xml.XMLParser.convert(XMLParser.java:316)
	at dr.xml.XMLParser.convert(XMLParser.java:287)
	at dr.xml.XMLParser.parse(XMLParser.java:166)
	at dr.app.beast.BeastMain.<init>(BeastMain.java:165)
	at dr.app.beast.BeastMain.main(BeastMain.java:805)

[1960.all.cc3.con.xml.zip](https://github.com/beast-dev/beast-mcmc/files/1202464/1960.all.cc3.con.xml.zip)

**Comment by rambaut** [comment]
From this point on, the lognormal can be parameterized as mean, stdev (in real space), or mu and sigma (the parameter of the underlying normal in log space). This issue was caused by some faulty logic trying to deal with 'meanInRealSpace' attribute to provide backwards compatibility. If this attribute is present then it changes how the mean and stdev parameters are interpreted (i.e., if false then mean is actually mu and stdev is actually sigma).
