### ISSUE TITLE
trunk won't compile

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#958]
In my machine, I get 

```
run program "codesign": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:41)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 23 more
```

With a "fresh" clone + ant.

**Comment by rambaut** [comment]
So it is not finding the 'codesign' utility which is a tool for Macs to cryptographically sign executables (and is obviously not present on Linux). The solution, I think is not to run the 'build' target (which calls the Mac packager) but just run the 'linux' target.

**Comment by rambaut** [comment]
Perhaps it is possible to include a conditional in the ant script to only allow the code signing if codesign is present.

**Comment by msuchard** [comment]
`ant linux` target does not appear to work either, per @plemey 

```
Using TreeDataLikelihood
Creating swap operator for parameter branchRates.categories (weight=10.0)
Optimization Schedule: log

Likelihood computation is using an auto sizing thread pool.
Exception in thread "main" java.lang.NoSuchMethodError: dr.inference.loggers.MCLogger.<init>(Ldr/inference/loggers/LogFormatter;IZI)V
```

**Comment by msuchard** [comment]
But, `ant dist` works on `travis-ci` to generate `beast.jar`.

**Comment by maxbiostat** [comment]
since `ant dist` also solves it for me, will close this for the time being.

**Comment by maxbiostat** [comment]
@msuchard @plemey  can I have the XML you guys were trying to run to see if I can run it on my system?

**Comment by plemey** [comment]
Don't mind sending, but it is for one of Marc's specific branches and i got it running in IntelliJ thanks to his suggestion (just not using a jar build from the branch for now)
