### ISSUE TITLE
Gibbs operator normalNormalMeanGibbsOperator returned a state with zero likelihood

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#963]
Fairly standard XML model with the normalNormalMeanGibbsOperator being used to estimate the parameters of an HPM.

Can't share the data / XML but am looking into this error.

State 28775349: A Gibbs operator, normalNormalMeanGibbsOperator, returned a state with zero likelihood.
Exception in thread "Thread-1" java.lang.RuntimeException: An error was encounted. Terminating BEAST
	at dr.util.ErrorLogHandler.publish(Unknown Source)
	at java.util.logging.Logger.log(Logger.java:610)
	at java.util.logging.Logger.doLog(Logger.java:631)
	at java.util.logging.Logger.log(Logger.java:654)
	at java.util.logging.Logger.severe(Logger.java:1140)
	at dr.inference.markovchain.MarkovChain.runChain(Unknown Source)
	at dr.inference.mcmc.MCMC.chain(Unknown Source)
	at dr.inference.mcmc.MCMC.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:744)

**Comment by GuyBaele** [comment]
Didn't encounter this any more; and also can't remember which data set generated this.
