### ISSUE TITLE
I can't open Beauti on my Mac

### ISSUE THREAD

**Issue by julianaosse** [beast-dev/beast-mcmc#981]
I installed the recommended Java version, but I cannot open Beauti and when I open Beast appears lines of erros:

Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/AboutHandler
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at jam.mac.Utils.macOSXRegistration(Unknown Source)
	at jam.console.ConsoleApplication.initialize(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 14 more

Is there anyone that can help me with this?

**Comment by rambaut** [comment]
This is an issue with previous versions of BEAUti (v1.8.4 or earlier) loading in Java 9. This is fixed in the master branch and will be in future releases.
