### ISSUE TITLE
1.10.0 "No acceptable BEAGLE library" despite -beagle_off

### ISSUE THREAD

**Issue by ilovezfs** [beast-dev/beast-mcmc#994]
```
iMac-TMP:~ joe$ brew test -vd beast
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/beast.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ant.rb
Testing beast
/usr/bin/sandbox-exec -f /tmp/homebrew20180613-58356-25l3my.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/beast.rb -vd
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/beast.rb
==> /usr/local/Cellar/beast/1.10.0/bin/beast -beagle_off testUCRelaxedClockLogNormal.xml
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/joe/Library/Caches/Homebrew/java_cache

                  BEAST v1.10.0, 2002-2018
       Bayesian Evolutionary Analysis Sampling Trees
                 Designed and developed by
   Alexei J. Drummond, Andrew Rambaut and Marc A. Suchard
                              
               Department of Computer Science
                   University of Auckland
                  alexei@cs.auckland.ac.nz
                              
             Institute of Evolutionary Biology
                  University of Edinburgh
                     a.rambaut@ed.ac.uk
                              
              David Geffen School of Medicine
           University of California, Los Angeles
                     msuchard@ucla.edu
                              
                Downloads, Help & Resources:
                  	http://beast.community
                              
Source code distributed under the GNU Lesser General Public License:
          	http://github.com/beast-dev/beast-mcmc
                              
                     BEAST developers:
	Alex Alekseyenko, Guy Baele, Trevor Bedford, Filip Bielejec, Erik Bloomquist, Matthew Hall,
	Joseph Heled, Sebastian Hoehna, Denise Kuehnert, Philippe Lemey, Wai Lok Sibon Li,
	Gerton Lunter, Sidney Markowitz, Vladimir Minin, Michael Defoin Platel,
          	Oliver Pybus, Chieh-Hsi Wu, Walter Xie
                              
                         Thanks to:
    	Roald Forsberg, Beth Shapiro and Korbinian Strimmer

Random number seed: 1528875667919

Failed to load parser: dr.inferencexml.model.FastBUTMPParser
line = dr.inferencexml.model.FastBUTMPParser



Failed to load parser: dr.evomodelxml.branchratemodel.RandomDiscretizedBranchRatesParser
line = dr.evomodelxml.branchratemodel.RandomDiscretizedBranchRatesParser



Failed to load parser: dr.evomodel.trace.DnDsPerSiteAnalysis
line = dr.evomodel.trace.DnDsPerSiteAnalysis


Failed to load parser: dr.evomodel.trace.CnCsPerSiteAnalysis
line = dr.evomodel.trace.CnCsPerSiteAnalysis


Failed to load parser: dr.evomodel.trace.CnCsToDnDsPerSiteAnalysis
line = dr.evomodel.trace.CnCsToDnDsPerSiteAnalysis


Failed to load parser: dr.evomodelxml.continuous.hmc.BranchRateGradientParser
line = dr.evomodelxml.continuous.hmc.BranchRateGradientParser

Loading additional development parsers from development_parsers.properties, which is additional set of parsers only available for development version ...

Failed to load parser: dr.evomodel.branchratemodel.TimeDependentBranchRates
line = dr.evomodel.branchratemodel.TimeDependentBranchRates


Failed to load parser: dr.evomodel.continuous.MissingInjection
line = dr.evomodel.continuous.MissingInjection


Failed to load parser: dr.evomodel.continuous.MissingInjectionLogger
line = dr.evomodel.continuous.MissingInjectionLogger

Parsing XML file: testUCRelaxedClockLogNormal.xml
  File encoding: ASCII
Looking for plugins in /private/tmp/beast-test-20180613-58357-5huy4j/plugins

Read alignment: alignment
  Sequences = 17
      Sites = 1485
   Datatype = nucleotide
Site patterns 'patterns' created from positions 1-1485 of alignment 'alignment'
  unique pattern count = 138

Creating the tree model, 'treeModel'
  taxon count = 17
  tree height = 1980.8764502501028

Using discretized relaxed clock model.
  over sampling = 1
  parametric model = logNormalDistributionModel
   rate categories = 1

Creating state frequencies model 'frequencies': Initial frequencies = {0.25, 0.25, 0.25, 0.25}

Creating HKY substitution model. Initial kappa = 2.0

Creating site rate model.

Using BEAGLE TreeLikelihood
  Branch rate model used: discretizedBranchRates
Failed to load BEAGLE library: no hmsbeagle-jni in java.library.path
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treelikelihood.BeagleTreeLikelihood.<init>(Unknown Source)
	at dr.evomodelxml.treelikelihood.BeagleTreeLikelihoodParser.createTreeLikelihood(Unknown Source)
	at dr.evomodelxml.treelikelihood.BeagleTreeLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /usr/local/Cellar/beast/1.10.0/bin/beast -beagle_off testUCRelaxedClockLogNormal.xml
```

**Comment by rambaut** [comment]
BEAST now requires BEAGLE for likelihood calculations. The Java version was only ever intended for testing as it is many-fold slower than BEAGLE. Will close this issue and add another one about removing the -beagle_off command line option.

**Comment by rambaut** [comment]
I will add that the Homebrew recipe needs to be updated to install BEAGLE as a dependency of BEAST (installing BEAST through Conda does this).

**Comment by ilovezfs** [comment]
CC @jonchang would you be willing to take a look at that please?

**Comment by rambaut** [comment]
The BEAST recipe is on Homebrew Core: https://github.com/Homebrew/homebrew-core/blob/master/Formula/beast.rb

**Comment by jonchang** [comment]
@ilovezfs I have a formula for `beagle` that I could upstream to homebrew/core if you would be interested in that. Or I can migrate `beast` into brewsci/bio. What do you think?

https://github.com/brewsci/homebrew-bio/blob/d0a71a833caab967846abd59e2be9e79f03a72ff/Formula/beagle.rb

**Comment by ilovezfs** [comment]
@jonchang either seems fine to me, whichever you prefer.

**Comment by ilovezfs** [comment]
@rambaut this is now fixed in Homebrew thanks to @jonchang. See

https://github.com/Homebrew/homebrew-core/pull/29247
https://github.com/Homebrew/homebrew-core/pull/29250
